# Generated by Django 4.0.3 on 2024-07-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0002_image_user_delete_hotel_image_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='img_name',
        ),
    ]
