# Generated by Django 4.0.3 on 2024-07-18 19:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0006_user_blood_group_user_ph_no_alter_image_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 18, 19, 41, 14, 435235, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='blood_group',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
